FC-InnerCircle-ICD2/fintech-BE

- build.gradle.kts
- src/main/resources/application.yaml
- src/main/resources/bootstrap.yml
> secret manager 설정

- api/src/main/kotlin/com/inner/circle/api/healthcheck/controller/HealthCheckController.kt
테스트 용 헬스 체크 컨트롤러 추가
> 티켓 번호 : #19 closed
> feat: 테스트용 health check 컨트롤러 추가

- api/src/main/kotlin/com/inner/circle/api/healthcheck/controller/HealthCheckController.kt
> feat: 테스트용 health check 컨트롤러 추가 (#19)

- api/src/main/kotlin/com/inner/circle/api/ApiApplication.kt
- api/src/main/kotlin/com/inner/circle/api/structure/PaymentController.kt
- api/src/main/kotlin/com/inner/circle/api/structure/dto/PaymentRequest.kt
- buildSrc/gradle.properties
- core/build.gradle.kts
- core/src/main/kotlin/com/inner/circle/core/structure/domain/Payment.kt
- core/src/main/kotlin/com/inner/circle/core/structure/service/PaymentService.kt
- core/src/main/kotlin/com/inner/circle/core/structure/usecase/RequestPaymentUseCase.kt
- gradle.properties
- infra/build.gradle.kts
- infra/src/main/kotlin/com/inner/circle/infra/structure/adaptor/PaymentAdaptor.kt
- infra/src/main/kotlin/com/inner/circle/infra/structure/adaptor/dto/PaymentSaveDto.kt
- infra/src/main/kotlin/com/inner/circle/infra/structure/port/SavePaymentPort.kt
- infra/src/main/kotlin/com/inner/circle/infra/structure/repository/PaymentMemoryRepository.kt
- infra/src/main/kotlin/com/inner/circle/infra/structure/repository/PaymentRepository.kt
- infra/src/main/kotlin/com/inner/circle/infra/structure/repository/entity/PaymentEntity.kt
- settings.gradle.kts
> #27/feat/package structure

- .github/CODEOWNERS
Fintech-BE Reviewer 지정을 위해 CODEOWNER 파일 추가
> 티켓 번호 : #31
> feat(ci): CODEOWNERS 파일 추가

- README.md
FE 문서에 대한 링크 추가
> 티켓 번호 : # {}
> Update README.md ver.2

- api/src/main/resources/application.yaml
간단한거라 티켓 생성은 하지 않았습니다 !
yaml 문법에 맞게 수정 하였습니다.
> api yaml 문법에 맞게 수정

- infra/build.gradle.kts
- infra/src/main/resources/application-postgres.yaml
> No Arg Plug in 추가 및 엔티티 명 단수로 변경

- api-backoffice/build.gradle.kts
- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/ApiBackofficeApplication.kt
- api-backoffice/src/main/resources/application.yaml
- api-backoffice/src/test/kotlin/com/inner/circle/apibackoffice/TestApiBackofficeApplication.kt
- api-backoffice/src/test/kotlin/com/inner/circle/apibackoffice/config/PostgreSqlTestContainerConfiguration.kt
- gradle/libs.versions.toml
- testcontainer를 활용한 local postgresql 구축
- AWS DB instance에 직접 붙지 않고도 로컬 환경에서 개발이 가능하도록 추가
- Postgresql을 사용하기 위한 여러 설정 파일 추가 (gradle, datasource.yaml, ...)
> 티켓 번호 : #57
> feat: Postsql local docker 환경 구축

- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/structure/AccountController.kt
- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/structure/dto/AccountRequest.kt
- api-backoffice/src/main/resources/application.yaml
- api-backoffice/src/test/kotlin/com/inner/circle/apibackoffice/config/PostgreSqlTestContainerConfiguration.kt
- core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/structure/domain/Account.kt
- core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/structure/service/AccountService.kt
- core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/structure/usecase/RequestAccountUseCase.kt
- infra-backoffice/build.gradle.kts
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/structure/adaptor/AccountAdaptor.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/structure/port/SaveAccountPort.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/structure/repository/AccountJpaRepository.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/structure/repository/AccountRepository.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/structure/repository/AccountRepositoryImpl.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/structure/repository/JpaConfiguration.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/structure/repository/entity/AccountEntity.kt
- infra-backoffice/src/main/resources/application-datasource.yaml
컨테이너 재사용을 위한 설정 변경
> 티켓 번호 : #57
> fix: 컨테이너 재사용을 위한 코드 변경

- api-backoffice/build.gradle.kts
- api/build.gradle.kts
- api/src/main/kotlin/com/inner/circle/api/common/response/AppExceptionResponse.kt
- api/src/main/kotlin/com/inner/circle/api/payment/exception/GlobalExceptionHandler.kt
- core-backoffice/build.gradle.kts
- core/build.gradle.kts
- exception/src/main/kotlin/com/inner/circle/exception/AppException.kt
- exception/src/main/kotlin/com/inner/circle/exception/HttpStatus.kt
- exception/src/main/kotlin/com/inner/circle/exception/PaymentException.kt
- infra-backoffice/build.gradle.kts
- infra/build.gradle.kts
- settings.gradle.kts
Exception  클래스 및 공통 Common Response 추가
해당 Exception 발생 시 공통 코드로 Response  맞추었습니다 !             
`{"code":404,"message":"Order with ID OrderIdTest not found"}%
`
> 티켓 번호 : # {}
> Exception 모듈 및 공통 클래스 추가 

- infra/src/main/kotlin/com/inner/circle/infra/structure/adaptor/CardPaymentAuthAdaptor.kt
- infra/src/main/kotlin/com/inner/circle/infra/structure/config/ExternalClientConfig.kt
- infra/src/main/kotlin/com/inner/circle/infra/structure/externalApi/CardAuthClient.kt
Refactoring Card 인증 부분
> 티켓 번호 : # {}
> Refactoring 카드 인증

- api/src/main/kotlin/com/inner/circle/api/sse/controller/SseApiController.kt
- infra/src/main/kotlin/com/inner/circle/infra/structure/adaptor/MobilePaymentAdaptor.kt
- infra/src/main/kotlin/com/inner/circle/infra/structure/adaptor/SaveUserCardAdaptor.kt
- infra/src/main/kotlin/com/inner/circle/infra/structure/repository/PaymentRequestRepository.kt
- infra/src/main/kotlin/com/inner/circle/infra/structure/repository/PaymentRequestRepositoryImpl.kt
- infra/src/main/kotlin/com/inner/circle/infra/structure/repository/UserCardRepository.kt
- infra/src/main/kotlin/com/inner/circle/infra/structure/repository/UserCardRepositoryImpl.kt
Lint 가 정렬이 제대로 안되어 gradle build 가 안되고 있습니다 ㅜㅜ ! 
Lint 맞추는 커밋 올립니다 ㅎㅎ !
> 티켓 번호 : # {}
> chore: Source Lint 맞춤 및 ide warning 요소 제거

- api/src/main/resources/application.yaml
- infra/src/main/kotlin/com/inner/circle/infra/structure/config/ExternalClientConfig.kt
- infra/src/main/resources/application-infra.yaml
MockServer BaseUrl 을 property 로 관리 될 수 있도록 변경 하였습니다 ㅎㅎ ! 
> 티켓 번호 : # {92}
> feat: Mock Server Base Url 프로퍼티로 관리 되도록 변경

- infra-backoffice/src/main/resources/application-datasource.yaml
- infra/src/main/resources/application-infra.yaml
> chore: Log IDE Warning 요소 제거

- .github/workflows/ci-cd.yaml
- .github/workflows/wc-cd-01-deploy.yaml
- api-backoffice/src/main/resources/application.yaml
- api/src/main/resources/application.yaml
- gradle/libs.versions.toml
- infra-backoffice/build.gradle.kts
- infra-backoffice/src/main/resources/application-datasource.yaml
- infra/build.gradle.kts
- infra/src/main/resources/application-infra.yaml
> 시크릿매니저 관련 내용 추가

- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/BackofficeV1Api.kt
- exception/src/main/kotlin/com/inner/circle/exception/PaymentException.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/PaymentAdaptor.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/TransactionAdaptor.kt
> refactor: backoffice 리팩토링

- api/src/test/kotlin/com/inner/circle/api/TestApiPaymentApplication.kt
- api/src/test/kotlin/com/inner/circle/api/config/RedisTestContainerConfiguration.kt
- gradle/libs.versions.toml
- infra/build.gradle.kts
> #36 - @ : redis container setting

- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/HealthCheckController.kt
> feat: HealthCheck 로직 추가

- api/src/main/resources/application.yaml
- core/src/main/kotlin/com/inner/circle/core/service/ConfirmPaymentService.kt
- exception/src/main/kotlin/com/inner/circle/exception/PaymentException.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/PaymentRequestJpaRepository.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/PaymentRequestRepository.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/PaymentRequestRepositoryImpl.kt
대영님 httpclient 통신으로 변경한 코드입니다.
> 티켓 번호 : # {}
> 대영님 httpclient 통신으로 변경

- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/common/response/AppExceptionResponse.kt
- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/config/SwaggerConfig.kt
- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/exception/GlobalExceptionHandler.kt
- api-backoffice/src/main/resources/application-openapi.yaml
- api/src/main/kotlin/com/inner/circle/api/config/SwaggerConfig.kt
- api/src/main/resources/application-openapi.yaml
- api/src/main/resources/application.yaml
> fix: swagger 설정 변경

- api/src/main/kotlin/com/inner/circle/api/security/SecurityConfig.kt
> 티켓 번호 : # {}
스웨거 접속 및 api 호출 가능한지 한번 확인 해주시면 감사하겠습니다 🙇‍♀️
> Hotfix: SecurityConfig 설정 이슈 수정

- api/src/main/kotlin/com/inner/circle/api/security/SecurityConfig.kt
- core/src/main/kotlin/com/inner/circle/core/security/SecurityUserDetailsService.kt
- core/src/main/kotlin/com/inner/circle/core/service/ConfirmPaymentService.kt
- core/src/main/kotlin/com/inner/circle/core/service/SavePaymentApproveService.kt
린트 이슈 수정 방법 이해 못하고 있었나 봅니다ㅠㅠ 
ci/cd 이슈 발생 확인해서 린트 적용 후 다시 pr 요청합니다
> 티켓 번호 : # {}
> Spring Security Lint 이슈 수정

- api/src/main/kotlin/com/inner/circle/api/controller/SseApiController.kt
sse 파라미터 hidden = true => false로 변경
> 티켓 번호 : # {}
> 파라미터 숨김처리 해제

- api/src/main/kotlin/com/inner/circle/api/controller/SseApiController.kt
- api/src/main/kotlin/com/inner/circle/api/controller/request/ConfirmPaymentRequest.kt
- api/src/main/kotlin/com/inner/circle/api/controller/request/ConfirmSimplePaymentRequest.kt
- api/src/main/kotlin/com/inner/circle/api/controller/request/SsePaymentRequest.kt
get에 적합하게 reqeustParam으로 수정
> 티켓 번호 : # {}
> sse controller 수정

- infra/src/main/resources/application-infra.yaml
> build(ddl): ddl-auto : update 설정

- infra/src/main/kotlin/com/inner/circle/infra/repository/entity/PaymentEntity.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/entity/PaymentRequestEntity.kt
> 엔티티 오타 수정 입니다.

- api/build.gradle.kts
- api/src/main/kotlin/com/inner/circle/api/config/ObjectMapperConfig.kt
- api/src/test/kotlin/com/inner/circle/api/jackson/SerializationTest.kt
> DataClass 직렬화 문제 해결

- api/src/main/kotlin/com/inner/circle/api/controller/request/ConfirmPaymentRequest.kt
- api/src/main/kotlin/com/inner/circle/api/controller/request/ConfirmSimplePaymentRequest.kt
- api/src/main/kotlin/com/inner/circle/api/controller/request/PaymentApproveRequest.kt
> ObjectMappeer변경에 따른 Request 수정

- api/src/main/kotlin/com/inner/circle/api/config/ObjectMapperConfig.kt
- core/src/main/kotlin/com/inner/circle/core/service/ConfirmPaymentService.kt
- UUID -> TSID로 수정, 
- SSE 연결안되도 테스트 가능하게 수정
- snakeCase 삭제
> 티켓 번호 : # {}
> UUID -> TSID로 수정, 임시 SSE 수정

- api-backoffice/src/test/resources/sql/schema.sql
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/TransactionRepositoryImpl.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/entity/TransactionEntity.kt
- infra-backoffice/src/test/kotlin/com/inner/circle/infrabackoffice/repository/TransactionRepositoryTest.kt
테스트 깨지는 이슈 수정합니다.
> 티켓 번호 : #176
> fix(backoffice): 변경된 엔티티 테스트 코드 반영 

- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/PaymentController.kt
- api/src/main/kotlin/com/inner/circle/api/controller/merchant/MerchantPaymentController.kt
- api/src/main/kotlin/com/inner/circle/api/controller/user/UserPaymentController.kt
- core/src/main/kotlin/com/inner/circle/core/security/MerchantApiKeyProvider.kt
급히 동작만 할 수 있도록 수정
> 티켓 번호 : #fix/merchant.userdetails
> fix(payment): MerchantUserDetails 관련 오류 수정

- infra/src/main/kotlin/com/inner/circle/infra/repository/entity/UserCardEntity.kt
user_card Entity변경
> 티켓 번호 : # {}
> user_card Entity변경

- api/src/main/kotlin/com/inner/circle/api/controller/merchant/MerchantPaymentController.kt
- api/src/main/kotlin/com/inner/circle/api/controller/merchant/MerchantSseApiController.kt
- api/src/test/resources/sql/schema.sql
- core/src/main/kotlin/com/inner/circle/core/domain/PaymentInfo.kt
- core/src/main/kotlin/com/inner/circle/core/security/MerchantDetailService.kt
- core/src/main/kotlin/com/inner/circle/core/service/ConfirmPaymentService.kt
- core/src/main/kotlin/com/inner/circle/core/service/JwtHandler.kt
- core/src/main/kotlin/com/inner/circle/core/service/PaymentClaimService.kt
- core/src/main/kotlin/com/inner/circle/core/service/SavePaymentApproveService.kt
- core/src/main/kotlin/com/inner/circle/core/service/dto/PaymentInfoDto.kt
- core/src/main/kotlin/com/inner/circle/core/service/dto/PaymentRequestDto.kt
- core/src/main/kotlin/com/inner/circle/core/usecase/PaymentClaimUseCase.kt
- infra/src/main/kotlin/com/inner/circle/infra/adaptor/ConfirmPaymentAdaptor.kt
- infra/src/main/kotlin/com/inner/circle/infra/adaptor/PaymentClaimAdaptor.kt
- infra/src/main/kotlin/com/inner/circle/infra/adaptor/SavePaymentRequestAdaptor.kt
- infra/src/main/kotlin/com/inner/circle/infra/adaptor/dto/ConfirmPaymentInfraDto.kt
- infra/src/main/kotlin/com/inner/circle/infra/adaptor/dto/PaymentClaimDto.kt
- infra/src/main/kotlin/com/inner/circle/infra/adaptor/dto/PaymentTokenDto.kt
- infra/src/main/kotlin/com/inner/circle/infra/port/PaymentClaimHandlingPort.kt
- infra/src/main/kotlin/com/inner/circle/infra/port/SavePaymentRequestPort.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/entity/PaymentRequestEntity.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/entity/PaymentStatusType.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/entity/PaymentTokenEntity.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/entity/PaymentTokenRepository.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/memorydatabase/PaymentTokenMemoryRepository.kt
- merchantName 추가
- jwt 토큰 내 merchant_name 추가
> 티켓 번호 : #156
> fix(156): 결제 요청 로직 점검 - 결제 요청 시 merchant_name 저장되도록 수정

- api/src/main/kotlin/com/inner/circle/api/security/SecurityConfig.kt
> hotfix: conflict 이슈 수정

- api/src/main/kotlin/com/inner/circle/api/config/SwaggerConfig.kt
- api/src/main/kotlin/com/inner/circle/api/controller/merchant/MerchantSseApiController.kt
> feat: SSE 어노테이션 추가

- exception/src/main/kotlin/com/inner/circle/exception/PaymentException.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/CreateOrUpdateMerchantKeyAdaptor.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/dto/MerchantDto.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/MerchantRepositoryImpl.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/entity/MerchantEntity.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/entity/MerchantEntity.kt
Merchant Entity payment 쪽과 통합 PR입니다.
> 티켓 번호 : #211
> feat(backoffice): Merchant Entity payment쪽과 통합

- api/src/main/kotlin/com/inner/circle/api/controller/merchant/MerchantPaymentController.kt
- api/src/main/kotlin/com/inner/circle/api/controller/user/UserPaymentController.kt
> refactor(payment): User Card 관련 api 수정

- api-backoffice/src/test/kotlin/com/inner/circle/apibackoffice/config/PostgreSqlTestContainerConfiguration.kt
- api/src/test/kotlin/com/inner/circle/api/config/PostgreSqlTestContainerConfiguration.kt
- infra-backoffice/src/main/resources/application-datasource.yaml
> feat(backoffice): 개발 환경 통합

- api/src/main/kotlin/com/inner/circle/api/exception/GlobalExceptionHandler.kt
스웨거에 Error Code를 표현하기 위해 추가합니다.
> 티켓 번호 : #fix/swagger-error-code
> refactor(payment): Swagger Error code 정의

- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/MerchantController.kt
- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/dto/MerchantDto.kt
- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/dto/MerchantSignInDto.kt
- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/request/SignInMerchantRequest.kt
- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/request/SignUpMerchantRequest.kt
- core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/service/MerchantSaveService.kt
- core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/service/MerchantSignInService.kt
- core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/service/dto/MerchantDto.kt
- core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/service/dto/MerchantSignInDto.kt
- core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/usecase/MerchantSaveUseCase.kt
- core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/usecase/MerchantSignInUseCase.kt
- exception/src/main/kotlin/com/inner/circle/exception/BackofficeException.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/CreateOrUpdateMerchantKeyAdaptor.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/MerchantFinderAdaptor.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/MerchantSaveAdaptor.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/dto/MerchantDto.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/dto/MerchantKeyDto.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/port/CreateOrUpdateMerchantKeyPort.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/port/GetPaymentPort.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/port/MerchantFinderPort.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/port/MerchantSavePort.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/MerchantJpaRepository.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/MerchantRepository.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/MerchantRepositoryImpl.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/entity/MerchantEntity.kt
- 회원가입 request
```json
{
"username": "abce@nave.ocm",
"password": "test",
"name": "test"
}
```
- 회원가입 response
```json
{
"ok": true,
"data": {
"id": "197ec1d7-4111-40e6-bd52-e8216b318489",
"username": "abce@nave.ocm",
"password": "test",
"token": "AjdT2kouogZop1A_4rUUQzVpSm8t1lqjhquj8PD2UUI=",
"name": "test"
}
}
```
- 로그인 reqeust
```json
{
"username": "abce@nave.ocm",
"password": "test"
}
```
- 로그인  response
```json
{
"ok": true,
"data": {
"id": "197ec1d7-4111-40e6-bd52-e8216b318489",
"token": "AjdT2kouogZop1A_4rUUQzVpSm8t1lqjhquj8PD2UUI=",
"name": "test"
}
}
```
- 추후에 비밀번호 암호화 해서 저장하도록 수정되어야 할 것 같습니다!
> 티켓 번호 : # {}
> feat: 상점 회원가입/로그인 기능 구현

- core/src/main/kotlin/com/inner/circle/core/service/SavePaymentApproveService.kt
> 금액 상이 오류 수정

- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/MerchantController.kt
- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/dto/MerchantDto.kt
- core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/service/MerchantSaveService.kt
- core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/service/MerchantSignInService.kt
- core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/usecase/MerchantSaveUseCase.kt
- core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/usecase/MerchantSignInUseCase.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/CreateOrUpdateMerchantKeyAdaptor.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/MerchantFinderAdaptor.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/MerchantSaveAdaptor.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/port/MerchantFinderPort.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/port/MerchantSavePort.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/MerchantJpaRepository.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/MerchantRepository.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/MerchantRepositoryImpl.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/entity/MerchantEntity.kt
@youabledev 님께서 이미 고생해서 다 작업해 주신 내용 중 일부 수정할 부분은 없을까 살펴보았습니다~!
혹시 반영이 필요 없다면 close 하겠습니다~!
> 티켓 번호 : #fix/swagger-error-code
> refactor(backoffice): Merchant sign-in 관련 로직 부분 수정

- api/build.gradle.kts
- api/src/main/kotlin/com/inner/circle/api/config/BCryptPasswordEncoderConfig.kt
- api/src/main/kotlin/com/inner/circle/api/controller/dto/UserLoginResponse.kt
- api/src/main/kotlin/com/inner/circle/api/controller/request/UserLoginRequest.kt
- api/src/main/kotlin/com/inner/circle/api/controller/user/UserLoginController.kt
- api/src/main/kotlin/com/inner/circle/api/security/UserApiAuthenticationFilter.kt
- api/src/test/resources/sql/schema.sql
- core/src/main/kotlin/com/inner/circle/core/service/JwtHandler.kt
- core/src/main/kotlin/com/inner/circle/core/service/TokenHandlerService.kt
- core/src/main/kotlin/com/inner/circle/core/service/UserLoginService.kt
- core/src/main/kotlin/com/inner/circle/core/service/dto/AccountInfo.kt
- core/src/main/kotlin/com/inner/circle/core/usecase/TokenHandlerUseCase.kt
- core/src/main/kotlin/com/inner/circle/core/usecase/UserLoginUseCase.kt
- exception/src/main/kotlin/com/inner/circle/exception/UserAuthenticationException.kt
- gradle/libs.versions.toml
- infra/src/main/kotlin/com/inner/circle/infra/adaptor/AccountFinderAdaptor.kt
- infra/src/main/kotlin/com/inner/circle/infra/port/AccountFinderPort.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/UserRepository.kt
회원 로그인 기능 구현 하였습니다 ㅎㅎ !
- 해당 계정으로 Login Request 를 날려주면 Token 이 Response 되며 해당 Response 된 토큰으로 User API 를 이용하면 될 것 같습니다 ㅎㅎ !
- Token Validation 기능은 다음 PR 에 추가하도록 하겠습니다 !
> 티켓 번호 : # {}
> feat: User Login 기능 구현

- api/src/main/kotlin/com/inner/circle/api/controller/user/UserPaymentController.kt
- payment-in-progress 단계에서 sdk에 필요한 데이터 전달
> 티켓 번호 : #224
> fix(224): sse message type to json

- api/src/main/kotlin/com/inner/circle/api/controller/dto/PaymentType.kt
- api/src/main/kotlin/com/inner/circle/api/controller/dto/PaymentWithTransactionsDto.kt
- api/src/main/kotlin/com/inner/circle/api/controller/dto/TransactionDto.kt
- api/src/main/kotlin/com/inner/circle/api/controller/dto/TransactionStatus.kt
- api/src/main/kotlin/com/inner/circle/api/controller/user/UserPaymentController.kt
- core/src/main/kotlin/com/inner/circle/core/domain/PaymentTransaction.kt
- core/src/main/kotlin/com/inner/circle/core/domain/TransactionStatus.kt
- core/src/main/kotlin/com/inner/circle/core/service/TransactionService.kt
- core/src/main/kotlin/com/inner/circle/core/service/dto/PaymentWithTransactionsDto.kt
- core/src/main/kotlin/com/inner/circle/core/service/dto/TransactionDto.kt
- core/src/main/kotlin/com/inner/circle/core/usecase/GetPaymentWithTransactionsUseCase.kt
- exception/src/main/kotlin/com/inner/circle/exception/PaymentException.kt
- infra/src/main/kotlin/com/inner/circle/infra/adaptor/PaymentAdaptor.kt
- infra/src/main/kotlin/com/inner/circle/infra/adaptor/TransactionAdaptor.kt
- infra/src/main/kotlin/com/inner/circle/infra/adaptor/dto/TransactionDto.kt
- infra/src/main/kotlin/com/inner/circle/infra/port/GetPaymentPort.kt
- infra/src/main/kotlin/com/inner/circle/infra/port/GetTransactionPort.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/PaymentJpaRepository.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/PaymentRepository.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/PaymentRepositoryImpl.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/TransactionJpaRepository.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/TransactionRepository.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/TransactionRepositoryImpl.kt
간편 결제 유저의 결제 내역을 조회하는 API입니다.
> 티켓 번호 : #239
> feat(payment): 간편 결제 유저 - 결제 내역 조회

- api/src/test/resources/sql/schema.sql
> feat(testcontainer): user token 수정했습니다.

- api/src/main/kotlin/com/inner/circle/api/controller/dto/TransactionDto.kt
> fix(payment): TransactionDto 응답 반환 시 TSID String으로 변환

- api-backoffice/build.gradle.kts
- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/MerchantController.kt
- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/request/SignUpMerchantRequest.kt
- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/exception/GlobalExceptionHandler.kt
- api/src/main/kotlin/com/inner/circle/api/controller/request/UserLoginRequest.kt
- api/src/main/kotlin/com/inner/circle/api/controller/request/UserSignUpRequest.kt
- api/src/main/kotlin/com/inner/circle/api/controller/user/UserLoginController.kt
- api/src/main/kotlin/com/inner/circle/api/exception/GlobalExceptionHandler.kt
- api/src/main/kotlin/com/inner/circle/api/security/UserApiAuthenticationFilter.kt
- api/src/test/resources/sql/schema.sql
- core/src/main/kotlin/com/inner/circle/core/service/UserSignUpService.kt
- core/src/main/kotlin/com/inner/circle/core/usecase/UserSignUpUseCase.kt
- infra/src/main/kotlin/com/inner/circle/infra/adaptor/AccountFinderAdaptor.kt
- infra/src/main/kotlin/com/inner/circle/infra/adaptor/AccountSaveAdapter.kt
- infra/src/main/kotlin/com/inner/circle/infra/adaptor/AccountSaveAdaptor.kt
- infra/src/main/kotlin/com/inner/circle/infra/port/AccountSavePort.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/AccountRepository.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/entity/AccountEntity.kt
- infra/src/main/kotlin/com/inner/circle/infra/type/AccountStatus.kt
회원 가입 기능 추가 하였습니다 !
> 티켓 번호 : # {248}
> feat: 회원 가입 기능 추가

- core/src/main/kotlin/com/inner/circle/core/service/JwtHandler.kt
merchantId를 추가하여 sse 연결 등에서 활용할 수 있도록 한다.
> 티켓 번호 : #258
> fix(258): jwt payload 내 merchantId를 추가

- infra/src/main/kotlin/com/inner/circle/infra/adaptor/TransactionAdaptor.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/TransactionRepository.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/TransactionRepositoryImpl.kt
> fix(payment): transaction requestedAt 값 설정 로직 수정

- api/src/main/kotlin/com/inner/circle/api/controller/dto/UserInfoResponse.kt
- api/src/main/kotlin/com/inner/circle/api/controller/user/UserLoginController.kt
> feat: 현재 로그인한 회원 정보 조회 API 구현 

- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/ManagementController.kt
- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/security/MerchantApiKeyAuthenticationFilter.kt
- infra/src/test/kotlin/com/inner/circle/infra/adaptor/PaymentClaimAdaptorTest.kt
> fix(backoffice): 상점 api key 생성 시 로그인 토큰 활용

- core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/service/TransactionService.kt
- core/src/main/kotlin/com/inner/circle/core/service/TransactionService.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/PaymentRepositoryImpl.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/PaymentRepositoryImpl.kt
payment는 createdAt 기준 asc,
그 속의 transactions의 경우는 createdAt 기준 desc
> fix(payment, backoffice): payment 정렬 쿼리 수정

- api/src/main/kotlin/com/inner/circle/api/security/CustomAuthenticationEntryPoint.kt
- api/src/main/kotlin/com/inner/circle/api/security/MerchantApiKeyAuthenticationFilter.kt
- api/src/main/kotlin/com/inner/circle/api/security/SecurityConfig.kt
- api/src/main/kotlin/com/inner/circle/api/security/UserApiAuthenticationFilter.kt
간편 결제 인증 오류 시 500 에러가 아닌 401 응답
> fix(payment): user 인증 오류 시 메시지 출력

- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/exception/GlobalExceptionHandler.kt
- api/src/main/kotlin/com/inner/circle/api/config/ObjectMapperConfig.kt
- api/src/main/kotlin/com/inner/circle/api/controller/dto/PaymentResponse.kt
- api/src/main/kotlin/com/inner/circle/api/exception/GlobalExceptionHandler.kt
- infra/src/test/kotlin/com/inner/circle/infra/adaptor/PaymentClaimAdaptorTest.kt
ResponseEntityExceptionHandler 상속하여 MvcException 메시지 정제
> 티켓 번호 : #286
> feat(286/mvc-exception-handler): mvc 예외 처리 시 메시지 정제

- core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/service/JwtHandler.kt
- core/src/main/kotlin/com/inner/circle/core/service/JwtHandler.kt
에러 로그 출력이 보완되어야 하는 구간에 Exception을 추가하고 로거를 추가합니다.
> 티켓 번호 : #287
> fix(287): 예외 메시지가 보완되어야 할 구간 보완

- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/config/BCryptPasswordEncoderConfig.kt
- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/MerchantController.kt
- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/dto/MerchantSignInDto.kt
- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/security/AuthenticationExceptionHandlingFilter.kt
- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/security/SecurityConfig.kt
- core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/service/MerchantSaveService.kt
- core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/service/MerchantSignInService.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/MerchantFinderAdaptor.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/MerchantSaveAdaptor.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/port/MerchantFinderPort.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/MerchantJpaRepository.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/MerchantRepository.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/MerchantRepositoryImpl.kt
- infra/src/test/kotlin/com/inner/circle/infra/adaptor/PaymentClaimAdaptorTest.kt
- 백오피스 상점의 비밀번호 암호화 해서 관리
- 로그인 response에 id 추가
- 백오피스 인증/인가 500에러 BackofficeResponse 로 변경
> 티켓 번호 : #229
> fix: Spring Security 관련 이슈 수정

- api-backoffice/src/main/resources/application.yaml
- api-backoffice/src/main/resources/logback-spring.xml
backoffice 에 discord appender 추가하기
> 티켓 번호 : #161
> fix(161): discord-appender 추가 - backoffice

- api-backoffice/build.gradle.kts
backoffice 에 추가하기!
> 티켓 번호 : #161
> fix(161): discord-appender 추가 hotfix

- api/src/main/kotlin/com/inner/circle/api/controller/dto/UserCardDto.kt
- api/src/main/kotlin/com/inner/circle/api/controller/merchant/MerchantPaymentController.kt
- api/src/main/kotlin/com/inner/circle/api/controller/request/ConfirmPaymentRequest.kt
- api/src/main/kotlin/com/inner/circle/api/controller/request/UserCardRequest.kt
- api/src/main/kotlin/com/inner/circle/api/controller/user/UserPaymentController.kt
- core/src/main/kotlin/com/inner/circle/core/domain/PaymentInfo.kt
- core/src/main/kotlin/com/inner/circle/core/service/ConfirmPaymentService.kt
- core/src/main/kotlin/com/inner/circle/core/service/UserCardService.kt
- core/src/main/kotlin/com/inner/circle/core/service/dto/PaymentInfoDto.kt
- core/src/main/kotlin/com/inner/circle/core/service/dto/UserCardDto.kt
- core/src/main/kotlin/com/inner/circle/core/usecase/ConfirmPaymentUseCase.kt
- infra/src/main/kotlin/com/inner/circle/infra/adaptor/ConfirmPaymentAdaptor.kt
- infra/src/main/kotlin/com/inner/circle/infra/adaptor/UserCardAdaptor.kt
- infra/src/main/kotlin/com/inner/circle/infra/adaptor/dto/ConfirmPaymentInfraDto.kt
- infra/src/main/kotlin/com/inner/circle/infra/adaptor/dto/UserCardDto.kt
- infra/src/main/kotlin/com/inner/circle/infra/port/SaveUserCardPort.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/UserCardRepository.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/UserCardRepositoryImpl.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/entity/UserCardEntity.kt
카드사 추가에 따른 로직 변경
(DB도 변경 완료했습니다.)
> 티켓 번호 : # {}
> 카드사 추가에 따른 로직 변경

- infra/src/main/kotlin/com/inner/circle/infra/adaptor/ConfirmPaymentAdaptor.kt
> fix(306): 간편결제인증 - accountId를 구성

- core/src/main/kotlin/com/inner/circle/core/service/PaymentTokenHandleService.kt
PaymentTokenHandleService 로 리네이밍 처리.
> 티켓 번호 : #310
> refactor(310): payment token handle service 이름의 오타 바로잡습니다.

- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/PaymentController.kt
- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/dto/TransactionStatus.kt
- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/request/CancelPaymentRequest.kt
- core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/domain/TransactionStatus.kt
- core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/service/TransactionService.kt
- core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/service/dto/TransactionDto.kt
- core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/usecase/CancelPaymentUseCase.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/PaymentAdaptor.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/TransactionAdaptor.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/dto/PaymentDto.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/port/SaveTransactionPort.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/TransactionRepository.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/TransactionRepositoryImpl.kt
백오피스 결제 취소 기능 추가입니다.
> 이 작업이 merge 되면 앱 결제 취소도 모양을 맞춰 cancel로 통일하겠습니다.
> 티켓 번호 : #313
> feat(backoffice): 결제 취소 로직 추가

- core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/service/TransactionService.kt
- core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/usecase/GetPaymentWithTransactionsUseCase.kt
- core/src/main/kotlin/com/inner/circle/core/service/TransactionService.kt
- core/src/main/kotlin/com/inner/circle/core/usecase/GetPaymentWithTransactionsUseCase.kt
- exception/src/main/kotlin/com/inner/circle/exception/BackofficeException.kt
- exception/src/main/kotlin/com/inner/circle/exception/PaymentException.kt
우리는 UTC 기준으로 기준 시각을 잡았으나,
사용자 요청에 따른 현지 시각에 따른 검증을 위해 수정합니다.
> 티켓 번호 : #fix/validate-datetime
> fix(payment, backoffice): 요청 Locale에 따른 시간 검증 로직 수정

- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/PaymentController.kt
- api/src/main/kotlin/com/inner/circle/api/controller/merchant/MerchantPaymentController.kt
- api/src/main/kotlin/com/inner/circle/api/controller/user/UserPaymentController.kt
- core/src/main/kotlin/com/inner/circle/core/service/CancelPaymentRequestService.kt
- core/src/main/kotlin/com/inner/circle/core/usecase/CancelPaymentRequestUseCase.kt
결제 취소와 결제 요청 취소를 구분하기 위해 선작업입니다.
기능 수정은 없습니다.
클라이언트 분들과 협의 후 merge 하겠습니다!
> 티켓 번호 : #fix/rename-uri
> fix(payment): 결제 요청 취소 uri 변경

- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/exception/GlobalExceptionHandler.kt
- api-backoffice/src/main/resources/logback-spring.xml
- api/src/main/kotlin/com/inner/circle/api/exception/GlobalExceptionHandler.kt
- api/src/main/resources/logback-spring.xml
> feat(log level 조정): 불필요 로그는 discord appender에 미출력되도록 수정

- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/security/SecurityConfig.kt
- api/src/main/kotlin/com/inner/circle/api/security/SecurityConfig.kt
- MVC CORS setting을 사용
https://docs.spring.io/spring-security/reference/servlet/integrations/cors.html
Spring MVC CORS 설정으로 처리되도록 수정합니다.
> 티켓 번호 : # {}
> fix(infra/cors): cors config 를 security에서 제거

- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/security/SecurityConfig.kt
- api/src/main/kotlin/com/inner/circle/api/security/SecurityConfig.kt
> Revert "fix(infra/cors): cors config 를 security에서 제거 (#320)"

- core/src/main/kotlin/com/inner/circle/core/service/UserCardService.kt
- infra/src/main/kotlin/com/inner/circle/infra/adaptor/UserCardAdaptor.kt
> 중복 카드번호 예외처리

- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/config/WebConfig.kt
- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/security/SecurityConfig.kt
- api/src/main/kotlin/com/inner/circle/api/config/WebConfig.kt
- api/src/main/kotlin/com/inner/circle/api/security/SecurityConfig.kt
CORS PATCH 허용 추가
> 티켓 번호 : # {}
> CORS PATCH 허용 추가

- api-backoffice/src/main/resources/logback-spring.xml
- api/src/main/resources/logback-spring.xml
Reverts FC-InnerCircle-ICD2/fintech-BE#333
> Revert "중복 로그 방지"

- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/PaymentRepositoryImpl.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/PaymentRepositoryImpl.kt
* 필터링 조건 검색을 만들다, 가장 중요한 필터링 조건을 빼먹었네요 ㅎㅎ;
> 티켓 번호 : #fix/get-transactions-condition
> fix(payment, backoffice): 결제 내역 조회 필터링 조건 수정

- core/src/main/kotlin/com/inner/circle/core/service/UserCardService.kt
- exception/src/main/kotlin/com/inner/circle/exception/CardCompanyException.kt
- infra/src/main/kotlin/com/inner/circle/infra/http/HttpClient.kt
카드 등록 시 발급된 카드인지 확인
> 티켓 번호 : # {}
> 카드 등록 시 발급된 카드인지 확인

- api/src/main/kotlin/com/inner/circle/api/controller/merchant/MerchantPaymentController.kt
- api/src/main/kotlin/com/inner/circle/api/controller/user/UserPaymentController.kt
- api/src/test/resources/sql/schema.sql
- core/src/main/kotlin/com/inner/circle/core/service/TransactionService.kt
- core/src/main/kotlin/com/inner/circle/core/usecase/CancelPaymentUseCase.kt
- infra/src/main/kotlin/com/inner/circle/infra/adaptor/PaymentAdaptor.kt
- infra/src/main/kotlin/com/inner/circle/infra/port/GetPaymentPort.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/PaymentJpaRepository.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/PaymentRepository.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/PaymentRepositoryImpl.kt
상점에서 직접 결제 취소 요청을 보낼 수 있도록 수정
* 기존 user 용 결제 취소는 기능 상 의미가 없어 기능을 merchat로 옮김.
> 티켓 번호 : #refact/payment-cancel
> refactor(payment): 상점 BE용 결제 취소 API 추가

- infra/src/main/kotlin/com/inner/circle/infra/repository/UserCardJpaRepository.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/UserCardRepositoryImpl.kt
카드 최신순으로 정렬
주 카드 삭제 후 마지막으로 등록한 카드가 주 카드로 설정
> 티켓 번호 : # {}
> 카드 최신순으로 정렬

- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/PaymentController.kt
- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/dto/BackofficeResponse.kt
- api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/exception/GlobalExceptionHandler.kt
- api/src/main/kotlin/com/inner/circle/api/controller/user/UserPaymentController.kt
- api/src/main/kotlin/com/inner/circle/api/exception/GlobalExceptionHandler.kt
- core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/service/TransactionService.kt
- core/src/main/kotlin/com/inner/circle/core/service/TransactionService.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/PaymentAdaptor.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/TransactionAdaptor.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/PaymentRepository.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/PaymentRepositoryImpl.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/TransactionJpaRepository.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/TransactionRepository.kt
- infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/TransactionRepositoryImpl.kt
- infra/src/main/kotlin/com/inner/circle/infra/adaptor/PaymentAdaptor.kt
- infra/src/main/kotlin/com/inner/circle/infra/adaptor/TransactionAdaptor.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/PaymentRepository.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/PaymentRepositoryImpl.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/TransactionJpaRepository.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/TransactionRepository.kt
- infra/src/main/kotlin/com/inner/circle/infra/repository/TransactionRepositoryImpl.kt
결제 내역 조회 정렬 방식을 desc로 수정합니다.
> 티켓 번호 : #refactor/get-transactions-order-by
> refactor(payment, backoffice): 결제 내역 조회 정렬 방식 수정

- core/src/main/kotlin/com/inner/circle/core/service/JwtHandler.kt
JWT Token으로 merchantId 전달 시 toString() 으로 전달
> 티켓 번호 : # {}
> fix(hotfix/jwt-merchant-id): merchantId 변경되는 부분 hotfix

- core/src/main/kotlin/com/inner/circle/core/sse/SseConnectionPool.kt
> fix/sse-log(payment): SSE 관련 로그 확인

- api/build.gradle.kts
- api/src/main/kotlin/com/inner/circle/api/application/PaymentStatusChangedMessageSender.kt
- api/src/main/kotlin/com/inner/circle/api/controller/merchant/MerchantPaymentController.kt
- core/src/main/kotlin/com/inner/circle/core/sse/ConnectionPool.kt
- core/src/main/kotlin/com/inner/circle/core/sse/SseConnection.kt
- core/src/main/kotlin/com/inner/circle/core/sse/SseConnectionPool.kt
> 티켓 번호 : #refactor/connection-pool-remove
> refactor(payment): SSE ConnectionPool 제거 로직 수정

- api/src/main/resources/application-openapi.yaml
- api/src/main/resources/application.yaml
- core/src/main/resources/application-core.yaml
스프링부트 비동기 요청 타임아웃 1분 -> 3분으로 증대
> 티켓 번호 : # {}
> 스프링부트 비동기 요청 타임아웃 1분 -> 3분으로 증대

- api/src/main/kotlin/com/inner/circle/api/application/PaymentStatusChangedMessageSender.kt
- api/src/main/kotlin/com/inner/circle/api/controller/merchant/MerchantSseApiController.kt
- api/src/main/kotlin/com/inner/circle/api/controller/user/UserSseApiController.kt
> 임시 로직 비활성화 및 로그 레벨 상향

- api/src/main/kotlin/com/inner/circle/api/application/PaymentStatusChangedMessageSender.kt
- api/src/main/kotlin/com/inner/circle/api/application/dto/PaymentStatusChangedResponse.kt
- api/src/main/kotlin/com/inner/circle/api/application/dto/PaymentStatusChangedSsePaymentRequest.kt
- api/src/main/kotlin/com/inner/circle/api/controller/merchant/MerchantPaymentController.kt
- api/src/main/kotlin/com/inner/circle/api/controller/merchant/MerchantSseApiController.kt
- api/src/main/kotlin/com/inner/circle/api/controller/user/UserPaymentController.kt
- api/src/main/kotlin/com/inner/circle/api/controller/user/UserSseApiController.kt
- core/src/main/kotlin/com/inner/circle/core/sse/ConnectionPool.kt
- core/src/main/kotlin/com/inner/circle/core/sse/SseConnection.kt
- core/src/main/kotlin/com/inner/circle/core/sse/SseConnectionPool.kt
1. connection key 구성
2. connection key로 session만 제거 처리
- 로직 흐름 상 merchantId 만 가능.
> 티켓 번호 : #352
> fix(352): sse 로직 보완

- infra/src/main/kotlin/com/inner/circle/infra/repository/memorydatabase/PaymentTokenMemoryRepository.kt
> 티켓 번호 : #refact/payment-token-save-logic
> refactor(payment): redis call 줄이기
